export const APIUrlsConstants = {
    info: "/info",
    goal: "/goal",
    service: "/service",
    client: "/client",
    partner: "/partner",
    project: "/project",
    question: "/question",
    blog: "/blog",
    member: "/member",
    contact: "/contact",
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    changePassword: "/auth/change-password",
    changeEmail: "/auth/change-email",
};
